// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1q07kV94QlENiwTmksfh1Ec4WW6h6lAg',
    appId: '1:870820801286:web:9e54849e76c923c4a70c87',
    messagingSenderId: '870820801286',
    projectId: 'desamerdeka-9111c',
    authDomain: 'desamerdeka-9111c.firebaseapp.com',
    storageBucket: 'desamerdeka-9111c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzC7I25B6Wo7qZzWnpaYIxjmCuhZIcoQU',
    appId: '1:870820801286:android:7f949affcd5f19d9a70c87',
    messagingSenderId: '870820801286',
    projectId: 'desamerdeka-9111c',
    storageBucket: 'desamerdeka-9111c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnCmW9628SYNtVfC5P407jX9c9VqN8Vbo',
    appId: '1:870820801286:ios:8389e881ee455591a70c87',
    messagingSenderId: '870820801286',
    projectId: 'desamerdeka-9111c',
    storageBucket: 'desamerdeka-9111c.appspot.com',
    iosBundleId: 'com.example.desaMerdeka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnCmW9628SYNtVfC5P407jX9c9VqN8Vbo',
    appId: '1:870820801286:ios:8389e881ee455591a70c87',
    messagingSenderId: '870820801286',
    projectId: 'desamerdeka-9111c',
    storageBucket: 'desamerdeka-9111c.appspot.com',
    iosBundleId: 'com.example.desaMerdeka',
  );
}
